[package]
name = "iced_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = { version = "2.0.0" }
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.14.0-dev", features = [
    "auto-detect-theme",
    "system",
    "tokio",
    "image",
] }
image = { version = "0.25.6", optional = true }
native-dialog = { version = "0.9.0", optional = true }
rfd = { version = "0.15.3", optional = true }
tokio = { version = "1.46.1", features = ["rt-multi-thread"] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[features]
system_info = []
instax_framer = ["dep:rfd", "dep:native-dialog", "dep:image"]
counter = []
ddp = []

all = ["instax_framer", "system_info", "counter", "ddp"]

default = []
