[package]
name = "iced_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = { git = "https://github.com/frewsxcv/rust-dark-light.git", version = "1.1.1" }
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.13.0-dev", features = [
    "auto-detect-theme",
    "system",
    "tokio",
] }

[profile.release]
strip = true      # strip symbols from the binary
lto = true
codegen-units = 1
panic = "abort"
