[package]
name = "iced_counter"
version = "0.1.0"
edition = "2021"

[dependencies]
dark-light = { version = "2.0.0" }
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.14.0-dev", features = [
    "auto-detect-theme",
    "system",
    "tokio",
] }

[profile.release]
strip = true
lto = true
panic = "abort"
codegen-units = 1

[features]
system_info = []

counter = []
